import { describe, expect, it } from "vitest";
import { normaliseImportRow, productSchema } from "./schemas";

describe("normaliseImportRow", () => {
  it("accepts spreadsheet-style headers and drops unknown columns", () => {
    expect(
      normaliseImportRow({ Name: " Romper ", "Selling Price": 499, CATEGORY: "Clothing", Colour: "Mint", sku: null }),
    ).toEqual({ name: "Romper", selling_price: "499", category: "Clothing" });
  });
});

describe("productSchema", () => {
  const base = {
    id: null,
    name: "Romper",
    category: "CLOTHING" as const,
    sku: "",
    barcode: "",
    sellingPrice: "499",
    costPrice: "",
    reorderLevel: "0",
    supplierId: "",
    active: true,
  };

  it("accepts a minimal product (codes are generated by the database)", () => {
    expect(productSchema.safeParse(base).success).toBe(true);
  });

  it.each([
    [{ sellingPrice: "4.999" }, "Enter an amount like 499 or 499.50"],
    [{ reorderLevel: "-1" }, "Enter a whole number (0 for no reorder alert)."],
    [{ barcode: "AB 12" }, "Barcodes can't contain spaces or special characters."],
    [{ sku: "A B" }, "Use letters, numbers, and . _ / - only."],
  ])("rejects %o", (patch, message) => {
    const result = productSchema.safeParse({ ...base, ...patch });
    expect(result.success).toBe(false);
    expect(result.error?.issues[0]?.message).toBe(message);
  });
});
